import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0F1D', // Deep Obsidian Navy
    paddingHorizontal: 20,
    paddingTop: 54,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  headerLeft: {
    flex: 1,
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 2,
    fontWeight: '500',
  },
  badgeCount: {
    backgroundColor: '#0D9488', // Emerald Teal
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
  },
  badgeCountText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  contentContainer: {
    flex: 1,
    width: '100%',
    marginBottom: 95,
  },
  section: {
    marginBottom: 18,
    padding: 18,
    backgroundColor: '#131D31', // Polished dark surface
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#1E2F4D',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  transcriptSection: {
    backgroundColor: '#0B2236',
    borderColor: '#114B6E',
    borderLeftWidth: 4,
    borderLeftColor: '#06B6D4', // Vibrant Cyan
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#14B8A6', // Mint Teal
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  transcriptText: {
    fontSize: 15,
    color: '#E2E8F0',
    lineHeight: 23,
    fontStyle: 'italic',
  },
  tasksHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
    marginTop: 6,
  },
  tasksTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#F1F5F9',
    letterSpacing: -0.3,
  },
  clearAllText: {
    fontSize: 13,
    color: '#94A3B8',
    fontWeight: '500',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 45,
    paddingHorizontal: 20,
    backgroundColor: '#111827',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1F2937',
    borderStyle: 'dashed',
  },
  emptyIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#042F2E',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#E2E8F0',
    marginBottom: 6,
  },
  emptySubtitle: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 19,
  },
  todoItem: {
    marginBottom: 12,
    backgroundColor: '#131D31',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1E2F4D',
    borderLeftWidth: 4,
    borderLeftColor: '#10B981', // Emerald Accent
    flexDirection: 'row',
    alignItems: 'center',
  },
  todoItemCompleted: {
    borderLeftColor: '#64748B',
    opacity: 0.65,
    backgroundColor: '#0F172A',
  },
  checkboxContainer: {
    marginRight: 12,
  },
  taskContent: {
    flex: 1,
    marginRight: 8,
  },
  itemText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#F8FAFC',
    marginBottom: 6,
    lineHeight: 22,
  },
  itemTextCompleted: {
    textDecorationLine: 'line-through',
    color: '#94A3B8',
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  tagPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F2634',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#154A66',
  },
  tagPillTime: {
    backgroundColor: '#1C2719',
    borderColor: '#2D4E26',
  },
  tagText: {
    fontSize: 12,
    color: '#38BDF8',
    fontWeight: '500',
    marginLeft: 4,
  },
  tagTextTime: {
    color: '#4ADE80',
  },
  actionsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  actionButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#1E2F4D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteButton: {
    backgroundColor: '#371B26',
  },
  loadingContainer: {
    position: 'absolute',
    top: '38%',
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(10, 15, 29, 0.95)',
    paddingVertical: 24,
    paddingHorizontal: 32,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#14B8A6',
    zIndex: 20,
    shadowColor: '#14B8A6',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 15,
    elevation: 12,
  },
  loadingText: {
    marginTop: 14,
    color: '#14B8A6',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  waveformContainer: {
    position: 'absolute',
    bottom: 110,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 10,
  },
  waveformBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(10, 15, 29, 0.9)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#10B981',
    height: 48,
  },
  waveBar: {
    width: 4,
    backgroundColor: '#10B981',
    marginHorizontal: 2.5,
    borderRadius: 3,
  },
  bottomButtonContainer: {
    position: 'absolute',
    bottom: 24,
    left: 20,
    right: 20,
    backgroundColor: 'transparent',
  },
  buttonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  recordButton: {
    backgroundColor: '#0D9488', // Deep Emerald Teal
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    shadowColor: '#0D9488',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
    flex: 1,
  },
  stopButton: {
    backgroundColor: '#DC2626', // Vibrant Red
    shadowColor: '#DC2626',
  },
  cancelRecordButton: {
    backgroundColor: '#334155',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
    letterSpacing: 0.3,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
  },
  modalContent: {
    backgroundColor: '#131D31',
    padding: 24,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    width: '100%',
    borderWidth: 1,
    borderColor: '#1E2F4D',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#F8FAFC',
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#94A3B8',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  editInput: {
    backgroundColor: '#0A0F1D',
    color: '#F8FAFC',
    padding: 14,
    borderRadius: 12,
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#1E2F4D',
    marginBottom: 16,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 8,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: '#1E293B',
  },
  saveButton: {
    backgroundColor: '#0D9488',
  },
  modalButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
});

export default styles;
